### ISSUE TITLE
double tap zooming issue in iOS 8

### ISSUE THREAD

**Issue by kiddomk** [ideaismobile/IDMPhotoBrowser#102]
seems like a easy fix.
please refer to this
https://github.com/mwaterfall/MWPhotoBrowser/issues/304

simply added: 
+- (void)scrollViewDidZoom:(UIScrollView *)scrollView {
-    [self setNeedsLayout];
-    [self layoutIfNeeded];
  +}

**Comment by ancoo** [comment]
good
