### ISSUE TITLE
Linker Error _OBJC_CLASS_$IDMPhoto and IDMPhotoBrowser

### ISSUE THREAD

**Issue by chmiiller** [ideaismobile/IDMPhotoBrowser#12]
Hey man,

Im probably doing something wrong here, but I'm getting 3 Linker errors on my project.
I imported all the classes to my project and tried to make a simple displayer, made the 
# import "IDMPhotoBrowser.h"  and wrote the code.

Ill attach some images that might help you in helping me :)
Thanks very much.

![screen shot 2013-08-23 at 6 16 51 pm](https://f.cloud.github.com/assets/1013632/1019397/c2549760-0c41-11e3-966c-c2795e011cf6.png)

![screen shot 2013-08-23 at 6 16 26 pm](https://f.cloud.github.com/assets/1013632/1019398/c253ad6e-0c41-11e3-85d1-8ea19c5b9e8b.png)

![screen shot 2013-08-23 at 6 16 38 pm](https://f.cloud.github.com/assets/1013632/1019399/c25501f0-0c41-11e3-8d40-493737589abe.png)

**Comment by Aster0id** [comment]
Hey guns,I has this issue.But I wan't use cocoapods .
![qq20150122-1 2x](https://cloud.githubusercontent.com/assets/2233321/5849331/72c16dde-a21f-11e4-927a-29455aef0520.png)
Thanks
