### ISSUE TITLE
small image

### ISSUE THREAD

**Issue by timlai** [ideaismobile/IDMPhotoBrowser#126]
For very small image, the code below will cause maxScale < minScale in IDMZoomingScrollView

    CGFloat maxScale = 4.0; // Allow double scale
     // on high resolution screens we have double the pixel density, so we will be seeing every pixel if we limit the
    // maximum zoom scale to 0.5.
    if ([UIScreen instancesRespondToSelector:@selector(scale)]) {
        maxScale = maxScale / [[UIScreen mainScreen] scale];
    }

To prevent this happen, add something like this
        `if (maxScale < minScale) { maxScale = minScale * 2;}`

**Comment by eduardocallado** [comment]
I just released a new 1.6.2 version with this fix. Thanks!
