### ISSUE TITLE
Deprecated warning when iOS Deployment Target is iOS 8.0

### ISSUE THREAD

**Issue by juancds** [ideaismobile/IDMPhotoBrowser#128]
IDMPhotoBrowser.m:

'setCompletionHandler:' is deprecated: first deprecated in iOS 8.0 - Use 'completionWithItemsHandler' instead.

**Comment by svtechnology** [comment]
In IDMPhotoBrowser.m, replace

     __typeof__(self) __weak selfBlock = self;
                [self.activityViewController setCompletionHandler:^(NSString *activityType, BOOL completed) {
                    [selfBlock hideControlsAfterDelay];
                    selfBlock.activityViewController = nil;
                }];

with

    __typeof__(self) __weak selfBlock = self;
                [self.activityViewController setCompletionWithItemsHandler:^(NSString *activityType, BOOL completed, NSArray *returnedItems, NSError *activityError) {
                    [selfBlock hideControlsAfterDelay];
                    selfBlock.activityViewController = nil;
                }];

This should silence the compiler.

**Comment by eduardocallado** [comment]
Deprecated calling removed.
