### ISSUE TITLE
Pod not pointing to 1.7 version

### ISSUE THREAD

**Issue by mdelamata** [ideaismobile/IDMPhotoBrowser#150]
Hi,
I am using your Pod and unfortunately it downloads the previous tag (1.6.2). I think the .podspec has not being updated in their list or something. The .podspec in master points to v1.7 though.

Thank you very much.
Manuel.

**Comment by eduardocallado** [comment]
Fixed! Thanks for reporting!

**Comment by mdelamata** [comment]
:+1:
