### ISSUE TITLE
Resource bundle is not seen if "use_frameworks" is used in Podfile.

### ISSUE THREAD

**Issue by imadeit** [ideaismobile/IDMPhotoBrowser#176]
I tried to use IDMPhotoBrowser with Swift (>2.1) project, but I found if I enable using "use_frameworks" in the Podfile, the strings referenced from IDMPBLocalizations.bundle is not retrieved, (null) string is returned.
Then the expected "1 of 5" becomes "1 (null) 5", as well as the caption of Done button becomes empty.
Can you fix this problem?

**Comment by lehabaev** [comment]
Need help. I have the same problem...

**Comment by iCnSF** [comment]
I this it's pods' problem.
I delete IDMPhotoBrowserLocalizedStrings define.
But I'll change it in every update.  Can you fix this bug?

**Comment by jjsee** [comment]
Changing my IDMPhotoBrowser.m based on this merged commit https://github.com/ideaismobile/IDMPhotoBrowser/pull/161 worked for me. It fixes the entire localization issue IDMPhotoBrowser has.

@eduardocallado @thiagoperes It will be great if you can tag and release a new version for all the latest fixes. Thanks.

**Comment by eduardocallado** [comment]
I forgot to generate a new tag. Just did it, thanks for reminding!
