### ISSUE TITLE
Could I set images order?

### ISSUE THREAD

**Issue by ryan715** [ideaismobile/IDMPhotoBrowser#207]
Hi, I have a UICollectionView. When I click an image in UICollectionView, all the images add to IDMPhotoBrowser.photos, IDMPhotoBrowser  shows the first photo in photos. Is there any property or method can set the image order? I want the photo which I click to be first item.

**Comment by eduardocallado** [comment]
You can set the initial index using the setInitialPageIndex: method before presenting the PhotoBrowser.
