### ISSUE TITLE
Zoom scale is too large when image is long from side to side

### ISSUE THREAD

**Issue by yukitoto** [ideaismobile/IDMPhotoBrowser#214]
If the image is long from side to side, zoom scale become too large.

| Service |Original|Zoom|
|---|---|---|
|IDMPhotoBrowser|<img src="https://cloud.githubusercontent.com/assets/7534018/19020936/e0bca466-88f0-11e6-9816-f7870b3ada4c.jpg" width="250">|<img src="https://cloud.githubusercontent.com/assets/7534018/19020917/9dfcd8bc-88f0-11e6-8d7b-365ea38f69ac.jpg" width="250">|
| Facebook |<img src="https://cloud.githubusercontent.com/assets/7534018/19020889/f3c39f66-88ef-11e6-9c56-2af833a5fafa.jpg" width="250">|<img src="https://cloud.githubusercontent.com/assets/7534018/19020891/f8d0fc56-88ef-11e6-85f6-de196b615cb3.jpg" width="250">|

**Comment by yukitoto** [comment]
I create pull request for this issue.
https://github.com/ideaismobile/IDMPhotoBrowser/pull/215

**Comment by eduardocallado** [comment]
Merged, thank you!

**Comment by boreys** [comment]
thank you. this is what I am looking for too. I wonder how do I get this new merge? I'm using the cocoa pod

**Comment by eduardocallado** [comment]
I will generate the new tag/version later today. Ok?

**Comment by boreys** [comment]
thank you
