### ISSUE TITLE
crash when user taps the done button without waiting for the whole image to download

### ISSUE THREAD

**Issue by mythodeia** [ideaismobile/IDMPhotoBrowser#32]
Hello
i experienced a crash right when the user taps on a cell image, the modal opens and the progress is being shown to download an image from the web.
if you do not wait for the whole image to download and hit the DONE button the method performCloseAnimationWithScrollView crashes when setting the resizableImageView frame size, since the imageFromView is nil.

a solution would be an if statement like this:
if (imageFromView == nil) {
      // in case the user taps the DONE button without 
      // waiting for the whole image to download
       resizableImageView.frame = CGRectZero;
}
else{
      .......

if you find any better solution please share.

thanks

**Comment by iTofu** [comment]
I have the same problem and I checked the code, at `-[IDMPhotoBrowser performCloseAnimationWithScrollView:]` method, there are two lines:
```objc
float scaleX = senderViewOriginalFrame.size.width/scrollView.photoImageView.width;
float scaleY = senderViewOriginalFrame.size.height/scrollView.photoImageView.height;
```
`scrollView.photoImageView.width` and `scrollView.photoImageView.height` are both `0` when user taps the done button without waiting for the whole image to download, so it crashed.

My **solution** is that:
```objc
float scaleX = 0;
if (scrollView.photoImageView.width > 0) {
    scaleX = senderViewOriginalFrame.size.width/scrollView.photoImageView.width;
}
float scaleY = 0;
if (scrollView.photoImageView.height > 0) {
    scaleY = senderViewOriginalFrame.size.height/scrollView.photoImageView.height;
}
```
